xmsstamper: xms::XmStamper Class Reference
xms::XmStamper Class Reference
Performs a feature stamp operation.
#include <XmStamper.h>
Static Public Member Functions
static BSHP< XmStamper > New ()
Creates a XmStamper class.
Detailed Description
Performs a feature stamp operation.
See also
XmStamperImpl
Definition at line 40 of file XmStamper.h.
Member Function Documentation
New()
BSHP< XmStamper > xms::XmStamper::New () static
Creates a XmStamper class.
Returns
shared pointer to XmStamper.
Definition at line 551 of file XmStamper.cpp.
Referenced by XmStampIntermediateTests::test_SelfIntersect(), TutStampingUnitTests::test_StampCutEmbankment(), TutStampingUnitTests::test_StampFillEmbankment(), TutStampingUnitTests::test_StampGuidebank(), TutStampingUnitTests::test_StampIntersectBathymetry(), TutStampingUnitTests::test_StampSlopedAbutment(), and TutStampingUnitTests::test_StampWingWall().
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/XmStamper.h
/home/conan/xmsstamper/stamper/XmStamper.cpp