xmsstamper: xms::XmGuideBankUtilImpl Class Reference
xms::XmGuideBankUtilImpl Class Reference
Implementaion of XmGuideBankUtil.
Public Member Functions
virtual void DoConvertTo3d (bool a_first, XmStamperIo &a_io, XmStamper3dPts &a_3dpts) override
Converts an end cap to 3d pts defining the geometry.
virtual void GetEndCapEndPoints (cs3dPtIdx &a_ptIdx, VecInt &a_firstEndCapEndPts, VecInt &a_lastEndCapEndPts, XmStamperIo &a_io) override
creates a breakline representing the outer polygon of the stamp
virtual void GetEndCapBreakLines (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes) override
breaklines from the end cap
void GuideBankCenterLine ()
Creates the centerline for the guidebank.
void AdjustEndCapCrossSection ()
Creates a cross section to be used for the guide bank.
void CrossSectionTo3dPts ()
Creates a cross section to be used for the guide bank.
void GuideBankEndCap ()
Makes the cross sections for the end cap of the guide bank.
void BreakLinesAddCenterLine (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes)
breaklines from the center line
void BreakLinesAddEndPoints (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes)
breaklines the outer edge of the stamp
void BreakLinesAddCrossSections (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes)
breaklines for cross sections
void BreakLinesAddEndCap (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes)
breaklines for end cap
void BreakLinesAddShoulders (XmStamperIo &a_io, cs3dPtIdx &a_ptIdx, VecInt &a_blTypes)
breaklines for end cap
Public Attributes
bool m_first
flag indicating if this is from the first end of the stamp
XmStamperIo * m_io
io class that has the stamping inputs
XmStamper3dPts * m_3dpts
class that holds the 3d points from the stamp coversion
VecPt3d m_centerline
centerline for the guidebank
XmStampCrossSection m_cs
cross section for the guidebank
Additional Inherited Members
Static Public Member Functions inherited from xms::XmGuideBankUtil
static BSHP< XmGuideBankUtil > New ()
Creates a XmStampInterpCrossSection class.
Detailed Description
Implementaion of XmGuideBankUtil.
Converts a sloped abutment to 3d points for feature stamping.
Definition at line 46 of file XmGuideBankUtil.cpp.
Member Function Documentation
BreakLinesAddCenterLine()
void xms::XmGuideBankUtilImpl::BreakLinesAddCenterLine (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes)
breaklines from the center line
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 435 of file XmGuideBankUtil.cpp.
References xms::csPtIdx::m_centerLine, xms::cs3dPtIdx::m_centerLine, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::XmStamperIo::m_outBreakLines, and xms::XmStamperEndCap::m_type.
Referenced by GetEndCapBreakLines().
BreakLinesAddCrossSections()
void xms::XmGuideBankUtilImpl::BreakLinesAddCrossSections (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes)
breaklines for cross sections
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 557 of file XmGuideBankUtil.cpp.
References xms::csPtIdx::m_centerLine, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::csPtIdx::m_left, xms::XmStamperIo::m_outBreakLines, xms::csPtIdx::m_right, and xms::XmStamperEndCap::m_type.
Referenced by GetEndCapBreakLines().
BreakLinesAddEndCap()
void xms::XmGuideBankUtilImpl::BreakLinesAddEndCap (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes)
breaklines for end cap
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 620 of file XmGuideBankUtil.cpp.
References xms::csPtIdx::m_centerLine, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::csPtIdx::m_left, xms::XmStamperIo::m_outBreakLines, and xms::XmStamperEndCap::m_type.
Referenced by GetEndCapBreakLines().
BreakLinesAddEndPoints()
void xms::XmGuideBankUtilImpl::BreakLinesAddEndPoints (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes)
breaklines the outer edge of the stamp
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 476 of file XmGuideBankUtil.cpp.
References GetEndCapEndPoints(), xms::csPtIdx::m_centerLine, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::csPtIdx::m_left, xms::XmStamperIo::m_outBreakLines, xms::csPtIdx::m_right, xms::XmStamperEndCap::m_type, and xms::cs3dPtIdx::m_xsPts.
Referenced by GetEndCapBreakLines().
BreakLinesAddShoulders()
void xms::XmGuideBankUtilImpl::BreakLinesAddShoulders (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes)
breaklines for end cap
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 673 of file XmGuideBankUtil.cpp.
References xms::csPtIdx::m_centerLine, xms::XmStamperIo::m_cs, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::csPtIdx::m_left, xms::XmStamperIo::m_outBreakLines, xms::csPtIdx::m_right, xms::XmStamperEndCap::m_type, and xms::cs3dPtIdx::m_xsPts.
Referenced by GetEndCapBreakLines().
DoConvertTo3d()
void xms::XmGuideBankUtilImpl::DoConvertTo3d (bool a_first, XmStamperIo & a_io, XmStamper3dPts & a_3dpts) override virtual
Converts an end cap to 3d pts defining the geometry.
Parameters
[in] a_first - flag indicating if this is the first end cap (otherwise it is the last endcap)
[in] a_io - stamper io class
[out] a_3dpts - points filled in by the method
Definition at line 105 of file XmGuideBankUtil.cpp.
References AdjustEndCapCrossSection(), CrossSectionTo3dPts(), GuideBankCenterLine(), GuideBankEndCap(), m_3dpts, xms::XmStamperIo::m_centerLine, m_first, m_io, and XM_ENSURE_TRUE.
GetEndCapBreakLines()
void xms::XmGuideBankUtilImpl::GetEndCapBreakLines (XmStamperIo & a_io, cs3dPtIdx & a_ptIdx, VecInt & a_blTypes) override virtual
breaklines from the end cap
Parameters
[in,out] a_io StamperIo class
[in] a_ptIdx The indexes of the points in the TIN created by stamping
[out] a_blTypes The type of break line
Definition at line 419 of file XmGuideBankUtil.cpp.
References BreakLinesAddCenterLine(), BreakLinesAddCrossSections(), BreakLinesAddEndCap(), BreakLinesAddEndPoints(), and BreakLinesAddShoulders().
GetEndCapEndPoints()
void xms::XmGuideBankUtilImpl::GetEndCapEndPoints (cs3dPtIdx & a_ptIdx, VecInt & a_firstEndCapEndPts, VecInt & a_lastEndCapEndPts, XmStamperIo & a_io) override virtual
creates a breakline representing the outer polygon of the stamp
Parameters
[in] a_ptIdx The indexes of the points in the TIN
[out] a_firstEndCapEndPts first end cap ending points
[out] a_lastEndCapEndPts last end cap ending points
[in,out] a_io StamperIo class
Definition at line 341 of file XmGuideBankUtil.cpp.
References xms::csPtIdx::m_centerLine, xms::cs3dPtIdx::m_first_end_cap, xms::XmStamperIo::m_firstEndCap, xms::cs3dPtIdx::m_last_end_cap, xms::XmStamperIo::m_lastEndCap, xms::csPtIdx::m_left, xms::csPtIdx::m_right, and xms::XmStamperEndCap::m_type.
Referenced by BreakLinesAddEndPoints().
The documentation for this class was generated from the following file:
/home/conan/xmsstamper/stamper/detail/XmGuideBankUtil.cpp