xmsstamper: xms::XmBathymetryIntersector Class Reference
xms::XmBathymetryIntersector Class Reference
Intersects a feature stamp with a TIN.
#include <XmBathymetryIntersector.h>
Static Public Member Functions
static BSHP< XmBathymetryIntersector > New (BSHP< TrTin > a_tin, BSHP< TrTin > a_stamp)
Creates a XmStampInterpCrossSection class.
Detailed Description
Intersects a feature stamp with a TIN.
Definition at line 39 of file XmBathymetryIntersector.h.
Member Function Documentation
New()
BSHP< XmBathymetryIntersector > xms::XmBathymetryIntersector::New (BSHP< TrTin > a_tin, BSHP< TrTin > a_stamp) static
Creates a XmStampInterpCrossSection class.
Parameters
[in] a_tin The tin defining the bathymetry
[in] a_stamp The tin defined by the stamp
Returns
Shared ptr to a BathymetryIntersector
Definition at line 613 of file XmBathymetryIntersector.cpp.
References xms::XmBathymetryIntersectorImpl::XmBathymetryIntersectorImpl().
Referenced by xms::XmStamperImpl::CreateBathymetryIntersector(), and XmBathymetryIntersectorUnitTests::testCreateClass().
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/detail/XmBathymetryIntersector.h
/home/conan/xmsstamper/stamper/detail/XmBathymetryIntersector.cpp