xmsstamper: TutStampingUnitTests Class Reference
TutStampingUnitTests Class Reference
Tests stamping code.
Public Member Functions
void test_StampFillEmbankment ()
Tests stamping a simple fill embankment.
void test_StampCutEmbankment ()
Tests stamping a simple cut embankment.
void test_StampWingWall ()
Tests stamping a simple fill embankment with a wing wall end cap.
void test_StampSlopedAbutment ()
Tests stamping a simple fill embankment with sloped abutment end cap.
void test_StampGuidebank ()
Tests stamping a simple fill embankment with guidebank end cap.
void test_StampIntersectBathymetry ()
Tests stamping a simple fill embankment bathymetry cut off.
void test_RealDataStamping ()
[snip_testStampIntersectBathymetry]
Detailed Description
Tests stamping code.
[snip_testStampFillEmbankment]
Definition at line 22 of file TutStamping.t.h.
Member Function Documentation
test_RealDataStamping()
void TutStampingUnitTests::test_RealDataStamping ()
[snip_testStampIntersectBathymetry]
Tests stamping with real data from double pipe creek
Definition at line 517 of file TutStamping.cpp.
References xms::XmStamperEndCap::m_angle, xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStamperIo::m_firstEndCap, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStamperIo::m_lastEndCap, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmSlopedAbutment::m_maxX, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmSlopedAbutment::m_slope, xms::XmStamperEndCap::m_slopedAbutment, xms::XmStamperIo::m_stampingType, xms::XmStamperEndCap::m_type, xms::XmStamperEndCap::m_wingWall, xms::XmWingWall::m_wingWallAngle, xms::XmStamper::New(), xms::XmStampRaster::ReadFromFile(), and xms::XmStampRaster::WriteGridFile().
test_StampCutEmbankment()
void TutStampingUnitTests::test_StampCutEmbankment ()
Tests stamping a simple cut embankment.
[snip_testStampFillEmbankment] [snip_testStampCutEmbankment]
Definition at line 138 of file TutStamping.cpp.
References xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmStamperIo::m_outBreakLines, xms::XmStamperIo::m_outTin, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmStamperIo::m_stampingType, xms::XmStamper::New(), TS_ASSERT_DELTA_VECPT3D, TS_ASSERT_EQUALS_VEC, TS_ASSERT_TXT_FILES_EQUAL, xms::XmStampRaster::WriteGridFile(), and XM_NODATA.
test_StampGuidebank()
void TutStampingUnitTests::test_StampGuidebank ()
Tests stamping a simple fill embankment with guidebank end cap.
[snip_testStampSlopedAbutment] [snip_testStampGuidebank]
Definition at line 377 of file TutStamping.cpp.
References xms::XmStamperEndCap::m_angle, xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStamperIo::m_firstEndCap, xms::XmStamperEndCap::m_guidebank, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStamperIo::m_lastEndCap, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmGuidebank::m_nPts, xms::XmStamperIo::m_outTin, xms::XmGuidebank::m_radius1, xms::XmGuidebank::m_radius2, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmGuidebank::m_side, xms::XmStamperIo::m_stampingType, xms::XmStamperEndCap::m_type, xms::XmGuidebank::m_width, xms::XmStamper::New(), TS_ASSERT_TXT_FILES_EQUAL, xms::XmStampRaster::WriteGridFile(), and XM_NODATA.
test_StampIntersectBathymetry()
void TutStampingUnitTests::test_StampIntersectBathymetry ()
Tests stamping a simple fill embankment bathymetry cut off.
[snip_testStampGuidebank] [snip_testStampIntersectBathymetry]
Definition at line 447 of file TutStamping.cpp.
References xms::XmStamperIo::m_bathymetry, xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmStamperIo::m_outTin, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmStamperIo::m_stampingType, xms::TrTin::New(), xms::XmStamper::New(), TS_ASSERT_DELTA_VECPT3D, TS_ASSERT_TXT_FILES_EQUAL, xms::XmStampRaster::WriteGridFile(), and XM_NODATA.
test_StampSlopedAbutment()
void TutStampingUnitTests::test_StampSlopedAbutment ()
Tests stamping a simple fill embankment with sloped abutment end cap.
[snip_testStampWingWall] [snip_testStampSlopedAbutment]
Definition at line 298 of file TutStamping.cpp.
References xms::XmStamperEndCap::m_angle, xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStamperIo::m_firstEndCap, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStamperIo::m_lastEndCap, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmSlopedAbutment::m_maxX, xms::XmStamperIo::m_outTin, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmSlopedAbutment::m_slope, xms::XmStamperEndCap::m_slopedAbutment, xms::XmStamperIo::m_stampingType, xms::XmStamperEndCap::m_type, xms::XmStamper::New(), TS_ASSERT_DELTA_VECPT3D, TS_ASSERT_TXT_FILES_EQUAL, xms::XmStampRaster::WriteGridFile(), and XM_NODATA.
test_StampWingWall()
void TutStampingUnitTests::test_StampWingWall ()
Tests stamping a simple fill embankment with a wing wall end cap.
[snip_testStampCutEmbankment] [snip_testStampWingWall]
Definition at line 212 of file TutStamping.cpp.
References xms::XmStamperEndCap::m_angle, xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, xms::XmStamperIo::m_firstEndCap, xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStamperIo::m_lastEndCap, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmStamperIo::m_outBreakLines, xms::XmStamperIo::m_outTin, xms::XmStamperIo::m_raster, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, xms::XmStamperIo::m_stampingType, xms::XmStamperEndCap::m_wingWall, xms::XmWingWall::m_wingWallAngle, xms::XmStamper::New(), TS_ASSERT_DELTA_VECPT3D, TS_ASSERT_EQUALS_VEC, TS_ASSERT_TXT_FILES_EQUAL, xms::XmStampRaster::WriteGridFile(), and XM_NODATA.
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/TutStamping.t.h
/home/conan/xmsstamper/stamper/TutStamping.cpp