xmsstamper: xms::XmUtil Class Reference
xms::XmUtil Class Reference
Utility functions.
#include <XmUtil.h>
Static Public Member Functions
static void ConvertXsPointsTo3d (const Pt3d &a_cl, const VecPt2d &a_pts, double a_maxX, double a_angle, VecPt3d2d &a_3dpts)
Converts the left or right portion of a cross section data to 3d point locations using the angle from the center line and the max x value.
static void EnsureVectorAtMaxX (VecPt2d &a_pts, double a_maxX)
Makes sure the cross section goes to the maxX value.
static void GetAnglesFromCenterLine (size_t a_idx, const VecPt3d &a_cl, double &a_leftAngle, double &a_rightAngle)
Gets the angles of the left and right cross sections relative to the centerline.
static void ScaleCrossSectionXvals (XmStampCrossSection &a_xs, double a_factor)
Converts interpolated cross sections to 3d.
Detailed Description
Utility functions.
Definition at line 34 of file XmUtil.h.
Member Function Documentation
ConvertXsPointsTo3d()
void xms::XmUtil::ConvertXsPointsTo3d (const Pt3d & a_cl, const VecPt2d & a_pts, double a_maxX, double a_angle, VecPt3d2d & a_3dpts) static
Converts the left or right portion of a cross section data to 3d point locations using the angle from the center line and the max x value.
Parameters
[in] a_cl The location on the centerline for these cross section points
[in] a_pts The cross section points
[in] a_maxX The max X value for this portion of the cross section
[in] a_angle The angle of the cross section relative to the center line of the cross section
[out] a_3dpts (x,y,z) points that are filled by the this method
Definition at line 50 of file XmUtil.cpp.
References EnsureVectorAtMaxX(), xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::XmStamperImpl::ConvertCrossSectionsTo3d(), xms::XmSlopedAbutmentUtilImpl::ConvertTo3d(), and xms::XmGuideBankUtilImpl::CrossSectionTo3dPts().
EnsureVectorAtMaxX()
void xms::XmUtil::EnsureVectorAtMaxX (VecPt2d & a_pts, double a_maxX) static
Makes sure the cross section goes to the maxX value.
Parameters
[in,out] a_pts 2d points
[in] a_maxX Max x value
Definition at line 95 of file XmUtil.cpp.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by xms::XmGuideBankUtilImpl::AdjustEndCapCrossSection(), ConvertXsPointsTo3d(), xms::XmSlopedAbutmentUtilImpl::EnsureCrossSectionAtMaxX(), and XmUtilUnitTests::test_EnsureVectorAtMaxX().
GetAnglesFromCenterLine()
void xms::XmUtil::GetAnglesFromCenterLine (size_t a_idx, const VecPt3d & a_cl, double & a_leftAngle, double & a_rightAngle) static
Gets the angles of the left and right cross sections relative to the centerline.
Parameters
[in] a_idx Index of the current cross section
[in] a_cl Array of locations defining center line
[out] a_leftAngle The angle of the left cross section relative to the center line.
[out] a_rightAngle The angle of the right cross section relative to the center line.
Definition at line 154 of file XmUtil.cpp.
References gmBisectingAngle(), gmPerpendicularAngle(), and XM_ENSURE_TRUE.
Referenced by xms::XmStamperImpl::ConvertCrossSectionsTo3d(), and xms::XmGuideBankUtilImpl::CrossSectionTo3dPts().
ScaleCrossSectionXvals()
void xms::XmUtil::ScaleCrossSectionXvals (XmStampCrossSection & a_xs, double a_factor) static
Converts interpolated cross sections to 3d.
Parameters
[in,out] a_xs Cross section
[in] a_factor Value multiplied to each X val
Definition at line 81 of file XmUtil.cpp.
References xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmStampCrossSection::m_right, and xms::XmStampCrossSection::m_rightMax.
Referenced by xms::XmGuideBankUtilImpl::GuideBankEndCap(), and xms::XmSlopedAbutmentUtilImpl::InterpolateCrossSections().
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/detail/XmUtil.h
/home/conan/xmsstamper/stamper/detail/XmUtil.cpp