xmsstamper: xms::XmStampInterpCrossSectionImpl Class Reference
xms::XmStampInterpCrossSectionImpl Class Reference
Implementaion of XmStampInterpCrossSection.
Public Member Functions
virtual void InterpMissingCrossSections (XmStamperIo &a_) override
Interpolates the missing cross sections. Modifys the m_cs member of the XmStamperIo class that is passed to this method.
virtual bool ValidCrossSectionsExist (XmStamperIo &a_) override
Interpolates the missing cross sections. Modifys the m_cs member of the XmStamperIo class that is passed to this method.
virtual void InterpCs (XmStampCrossSection &a_prev, XmStampCrossSection &a_next, double a_percent, XmStampCrossSection &a_cs) override
Interpolates a cross section from 2 other cross sections using a weight (a_percent)
virtual void InterpFromCenterlineProfile (XmStamperIo &a_io, XmStamperCenterlineProfile &a_profile) override
Converts XmStamperCenterlineProfile class to XmStamperIo class inputs.
int FindFirstValidCrossSection ()
Finds the first valid cross section in the inputs.
int FindLastValidCrossSection ()
Finds the last valid cross section in the inputs.
int FindNextValidCrossSection (int a_idx)
Finds the first valid cross section after a_idx in the inputs.
void InterpCs (int a_prev, int a_next, double a_percent, XmStampCrossSection &a_cs)
Interpolates a cross section from 2 other cross sections using a weight (a_percent)
void InterpPts (VecPt2d &a_v1, int a_beg1, int a_end1, VecPt2d &a_v2, int a_beg2, int a_end2, double a_percent, VecPt2d &a_interpPts)
Interpolates part of 2 cross sections to part of a new cross section. Separate interpolations are done for the cross section between the center line and the shoulder and then from the shoulder to boundary of the cross section.
void CalcTvals (VecPt2d &a_v, int a_beg, int a_end, VecDbl &a_t)
Calculates parametric t values from a vector of x,y coords based on x.
Pt2d PtFromT (VecPt2d &a_v, int a_beg, VecDbl &a_t, double a_tval)
Calculates the x,y location of the point at a_tval.
Public Attributes
BSHP< Observer > m_observer
progress observer
XmStamperIo * m_io
pointer to the inputs to the stamp operation
Additional Inherited Members
Static Public Member Functions inherited from xms::XmStampInterpCrossSection
static BSHP< XmStampInterpCrossSection > New ()
Creates a XmStampInterpCrossSection class.
Detailed Description
Implementaion of XmStampInterpCrossSection.
Definition at line 45 of file XmStampInterpCrossSection.cpp.
Member Function Documentation
CalcTvals()
void xms::XmStampInterpCrossSectionImpl::CalcTvals (VecPt2d & a_v, int a_beg, int a_end, VecDbl & a_t)
Calculates parametric t values from a vector of x,y coords based on x.
Parameters
[in] a_v vector of x,y
[in] a_beg Index to the start of the section of a_v
[in] a_end Index to the end of the section of a_v
[out] a_t Vector of calculated t values
Definition at line 417 of file XmStampInterpCrossSection.cpp.
Referenced by InterpPts().
FindFirstValidCrossSection()
int xms::XmStampInterpCrossSectionImpl::FindFirstValidCrossSection ()
Finds the first valid cross section in the inputs.
Returns
The index to the first valid cross section in the inputs. -1 is returned if no valid cross sections exist.
Definition at line 174 of file XmStampInterpCrossSection.cpp.
References FindNextValidCrossSection().
Referenced by InterpMissingCrossSections(), and ValidCrossSectionsExist().
FindLastValidCrossSection()
int xms::XmStampInterpCrossSectionImpl::FindLastValidCrossSection ()
Finds the last valid cross section in the inputs.
Returns
The index to the last valid cross section in the inputs. -1 is returned if no valid cross sections exist.
Definition at line 183 of file XmStampInterpCrossSection.cpp.
References xms::XmStamperIo::m_cs, and m_io.
Referenced by InterpMissingCrossSections().
FindNextValidCrossSection()
int xms::XmStampInterpCrossSectionImpl::FindNextValidCrossSection (int a_idx)
Finds the first valid cross section after a_idx in the inputs.
Parameters
[in] a_idx Index used to find the next valid cross section
Returns
The index to the next valid cross section in the inputs. If none exists then -1 is returned.
Definition at line 202 of file XmStampInterpCrossSection.cpp.
References xms::XmStamperIo::m_cs, and m_io.
Referenced by FindFirstValidCrossSection(), and InterpMissingCrossSections().
InterpCs() [1/2]
void xms::XmStampInterpCrossSectionImpl::InterpCs (XmStampCrossSection & a_prev, XmStampCrossSection & a_next, double a_percent, XmStampCrossSection & a_cs) override virtual
Interpolates a cross section from 2 other cross sections using a weight (a_percent)
Parameters
[in] a_prev The first cross section used to interpolate.
[in] a_next The second cross section used to interpolate.
[in] a_percent Interpolation weight applied to the prev/next cross sections.
[out] a_cs The newly interpolated cross section.
Definition at line 244 of file XmStampInterpCrossSection.cpp.
References InterpPts(), xms::XmStampCrossSection::m_idxLeftShoulder, xms::XmStampCrossSection::m_idxRightShoulder, xms::XmStampCrossSection::m_left, xms::XmStampCrossSection::m_leftMax, xms::XmStampCrossSection::m_right, xms::XmStampCrossSection::m_rightMax, and XM_ENSURE_TRUE.
Referenced by InterpCs(), InterpFromCenterlineProfile(), and InterpMissingCrossSections().
InterpCs() [2/2]
void xms::XmStampInterpCrossSectionImpl::InterpCs (int a_prev, int a_next, double a_percent, XmStampCrossSection & a_cs)
Interpolates a cross section from 2 other cross sections using a weight (a_percent)
Parameters
[in] a_prev Index to the first cross section used to interpolate.
[in] a_next Index to the second cross section used to interpolate.
[in] a_percent Interpolation weight applied to the prev/next cross sections.
[out] a_cs The newly interpolated cross section.
Definition at line 227 of file XmStampInterpCrossSection.cpp.
References InterpCs(), xms::XmStamperIo::m_cs, and m_io.
InterpFromCenterlineProfile()
void xms::XmStampInterpCrossSectionImpl::InterpFromCenterlineProfile (XmStamperIo & a_io, XmStamperCenterlineProfile & a_profile) override virtual
Converts XmStamperCenterlineProfile class to XmStamperIo class inputs.
Parameters
[in,out] a_io The stamping input/output class
[in] a_profile The stamping centerline profile class
Definition at line 297 of file XmStampInterpCrossSection.cpp.
References InterpCs(), xms::XmStamperIo::m_centerLine, xms::XmStamperCenterlineProfile::m_cs, xms::XmStamperIo::m_cs, xms::XmStamperCenterlineProfile::m_distance, xms::XmStamperCenterlineProfile::m_elevation, Mdist(), xms::Pt3< T >::x, XM_ASSERT, XM_ENSURE_TRUE, and xms::Pt3< T >::y.
Referenced by XmStampInterpCrossSectionUnitTests::testInterpFromCenterlineProfile0().
InterpMissingCrossSections()
void xms::XmStampInterpCrossSectionImpl::InterpMissingCrossSections (XmStamperIo & a_) override virtual
Interpolates the missing cross sections. Modifys the m_cs member of the XmStamperIo class that is passed to this method.
Parameters
[in,out] a_ The inputs and outputs for the feature stamp operation
Definition at line 103 of file XmStampInterpCrossSection.cpp.
References FindFirstValidCrossSection(), FindLastValidCrossSection(), FindNextValidCrossSection(), gmXyDistance(), InterpCs(), xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, and m_io.
Referenced by XmStampInterpCrossSectionUnitTests::test0(), XmStampInterpCrossSectionUnitTests::test1(), and XmStampInterpCrossSectionUnitTests::testCrossSectionTutorial().
InterpPts()
void xms::XmStampInterpCrossSectionImpl::InterpPts (VecPt2d & a_v1, int a_beg1, int a_end1, VecPt2d & a_v2, int a_beg2, int a_end2, double a_percent, VecPt2d & a_interpPts)
Interpolates part of 2 cross sections to part of a new cross section. Separate interpolations are done for the cross section between the center line and the shoulder and then from the shoulder to boundary of the cross section.
Parameters
[in] a_v1 pts from the first cross section
[in] a_beg1 Index to the start of the section of a_v1
[in] a_end1 Index to the end of the section of a_v1
[in] a_v2 pts from the second cross section
[in] a_beg2 Index to the start of the section of a_v2
[in] a_end2 Index to the end of the section of a_v2
[in] a_percent Interpolation weight applied to the prev/next cross sections.
[out] a_interpPts Vector of newly interpolated points
Definition at line 382 of file XmStampInterpCrossSection.cpp.
References CalcTvals(), PtFromT(), xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by InterpCs().
PtFromT()
Pt2d xms::XmStampInterpCrossSectionImpl::PtFromT (VecPt2d & a_v, int a_beg, VecDbl & a_t, double a_tval)
Calculates the x,y location of the point at a_tval.
Parameters
[in] a_v vector of x,y
[in] a_beg Index to the start of the section of a_v
[in] a_t Vector of calculated t values
[in] a_tval Parametric tvalue
Returns
the x,y location of the point at a_tval
Definition at line 438 of file XmStampInterpCrossSection.cpp.
References xms::Pt2< T >::x, and xms::Pt2< T >::y.
Referenced by InterpPts().
ValidCrossSectionsExist()
bool xms::XmStampInterpCrossSectionImpl::ValidCrossSectionsExist (XmStamperIo & a_) override virtual
Interpolates the missing cross sections. Modifys the m_cs member of the XmStamperIo class that is passed to this method.
Parameters
[in,out] a_ The inputs and outputs for the feature stamp operation
Returns
true if there are any valid cross sections
Definition at line 162 of file XmStampInterpCrossSection.cpp.
References FindFirstValidCrossSection(), and m_io.
The documentation for this class was generated from the following file:
/home/conan/xmsstamper/stamper/detail/XmStampInterpCrossSection.cpp