xmsstamper: xms::XmStamperImpl Class Reference
xms::XmStamperImpl Class Reference
Performs a feature stamp operation The result of the operation is a TIN and a list of breakline segments.
Public Member Functions
virtual void DoStamp (XmStamperIo &a_io) override
Performs the feature stamping operation.
virtual void FillStamperIoFromCenterlineProfile (XmStamperIo &a_io, XmStamperCenterlineProfile &a_profile) override
Converts XmStamperCenterlineProfile class to XmStamperIo class inputs.
virtual const VecPt3d & GetPoints () override
returns the point locations created by the stamp operation.
virtual const VecInt2d & GetSegments () override
returns breaklines created by the stamp operation.
virtual const VecInt & GetBreaklineTypes () override
virtual void SetObserver (BSHP< Observer > a_) override
void WriteInputsForDebug ()
Writes the XmStamperIo class to a file for debugging.
bool InputErrorsFound ()
Checks for input errors.
void CreateBathymetryIntersector ()
Creates the intersector for the bathymetry.
void GetStampBounds ()
Gets the bounds of the stamp.
void IntersectCenterLineWithBathemetry ()
Intersects the center line with the bathemetry.
void InterpolateMissingCrossSections ()
Interpolates cross sections for any points that do not have a cross section specified.
void DecomposeCenterLine ()
Decomposes the centerline (more help needed)
void ConvertCrossSectionsTo3d ()
Converts the cross section data to 3d point locations.
void ConvertEndCapsTo3d ()
Converts the cross section data to 3d point locations.
void IntersectWithTin ()
Intersects the feature stampe with the elevation TIN.
bool CreateOutputs ()
Creates the output TIN and breaklines.
void AddCrossSectionPointsToArray (stXs3dPts &a_csPts, VecPt3d &a_pts, csPtIdx &a_ptIdx)
puts cross section points into a single array to be used by a TIN
bool CreateBreakLines (cs3dPtIdx &a_ptIdx)
Creates breaklines that will be honored in the TIN.
void AppendTinAndBreakLines (bool a_errors)
appends to the output TIN and breaklines
void Convert3dPtsToVec ()
puts all of the generated 3d points into one vector
Public Attributes
BSHP< Observer > m_observer
progress observer
XmStamperIo m_io
std::vector< XmStamperIo > m_vIo
vector of stampers to break up center line where intersections occur
BSHP< XmStampInterpCrossSection > m_interp
BSHP< XmBathymetryIntersector > m_intersect
class to intersect the feature stamp with bathemetry
BSHP< XmBreaklines > m_breaklineCreator
class to create breaklines
BSHP< VecPt3d > m_outPts
the output points
XmStamper3dPts m_3dpts
3d locations of the stamp operation
VecInt2d m_breaklines
breaklines
bool m_error
flag to indicate that an error has occurred processing the stamp
BSHP< TrTin > m_tin
tin created by the stamp operation
Pt3d m_stampBoundsMin
min x,y,z of stamp
Pt3d m_stampBoundsMax
max x,y,z of stamp
BSHP< VecPt3d > m_curPts
the output points
cs3dPtIdx m_ptIdx
indexes of point created from stamp
VecInt m_blTypes
type of breakline
Additional Inherited Members
Static Public Member Functions inherited from xms::XmStamper
static BSHP< XmStamper > New ()
Creates a XmStamper class.
Detailed Description
Performs a feature stamp operation The result of the operation is a TIN and a list of breakline segments.
Definition at line 56 of file XmStamper.cpp.
Member Function Documentation
AddCrossSectionPointsToArray()
void xms::XmStamperImpl::AddCrossSectionPointsToArray (stXs3dPts & a_csPts, VecPt3d & a_pts, csPtIdx & a_ptIdx)
puts cross section points into a single array to be used by a TIN
Parameters
[in] a_csPts Left and right points for cross sections
[out] a_pts The array of points for the TIN
[out] a_ptIdx The indexes of the points in the a_pts array
Definition at line 474 of file XmStamper.cpp.
References xms::stXs3dPts::m_centerLine, xms::csPtIdx::m_centerLine, xms::stXs3dPts::m_left, xms::csPtIdx::m_left, xms::stXs3dPts::m_right, and xms::csPtIdx::m_right.
Referenced by Convert3dPtsToVec().
AppendTinAndBreakLines()
void xms::XmStamperImpl::AppendTinAndBreakLines (bool a_errors)
appends to the output TIN and breaklines
Parameters
[in] a_errors flag indicating if there were errors creating the stamp
Definition at line 519 of file XmStamper.cpp.
References m_breaklines, m_error, m_io, xms::XmStamperIo::m_outBreakLines, m_outPts, xms::XmStamperIo::m_outTin, and m_tin.
Referenced by DoStamp().
CreateBreakLines()
bool xms::XmStamperImpl::CreateBreakLines (cs3dPtIdx & a_ptIdx)
Creates breaklines that will be honored in the TIN.
Parameters
[in] a_ptIdx The indexes of the points in the TIN
Returns
true if breaklines successfully created.
Definition at line 507 of file XmStamper.cpp.
References m_blTypes, m_breaklineCreator, m_io, and xms::XmBreaklines::New().
Referenced by CreateOutputs().
CreateOutputs()
bool xms::XmStamperImpl::CreateOutputs ()
Creates the output TIN and breaklines.
Returns
true on success.
Definition at line 421 of file XmStamper.cpp.
References Convert3dPtsToVec(), CreateBreakLines(), m_breaklineCreator, m_curPts, m_io, m_observer, xms::XmStamperIo::m_outBreakLines, xms::XmStamperIo::m_outTin, m_ptIdx, xms::TrTin::New(), xms::TrBreaklineAdder::New(), xms::TrOuterTriangleDeleter::New(), and xms::TrTriangulatorPoints::SetObserver().
Referenced by CreateBathymetryIntersector(), and DoStamp().
DoStamp()
void xms::XmStamperImpl::DoStamp (XmStamperIo & a_io) override virtual
Performs the feature stamping operation.
Parameters
a_io The stamping input/output class. When sucessful, the m_outTin and m_outBreakLines members of a_io are filled by this method.
Definition at line 205 of file XmStamper.cpp.
References AppendTinAndBreakLines(), ConvertCrossSectionsTo3d(), ConvertEndCapsTo3d(), CreateBathymetryIntersector(), CreateOutputs(), DecomposeCenterLine(), InputErrorsFound(), InterpolateMissingCrossSections(), IntersectCenterLineWithBathemetry(), IntersectWithTin(), m_3dpts, m_breaklineCreator, m_breaklines, m_error, m_io, xms::XmStamperIo::m_outBreakLines, m_outPts, xms::XmStamperIo::m_outTin, xms::XmStamperIo::m_raster, xms::XmStamperIo::m_stampingType, m_tin, xms::XmStampRaster::m_vals, m_vIo, xmlog::warning, WriteInputsForDebug(), and XM_LOG.
FillStamperIoFromCenterlineProfile()
void xms::XmStamperImpl::FillStamperIoFromCenterlineProfile (XmStamperIo & a_io, XmStamperCenterlineProfile & a_profile) override virtual
Converts XmStamperCenterlineProfile class to XmStamperIo class inputs.
Parameters
[in,out] a_io The stamping input/output class
[in] a_profile The stamping centerline profile class
Definition at line 259 of file XmStamper.cpp.
References m_interp.
GetBreaklineTypes()
virtual const VecInt& xms::XmStamperImpl::GetBreaklineTypes () inline override virtual
returns the type of breakline.
Returns
breakline types.
Definition at line 80 of file XmStamper.cpp.
References m_blTypes.
GetPoints()
virtual const VecPt3d& xms::XmStamperImpl::GetPoints () inline override virtual
returns the point locations created by the stamp operation.
Returns
points.
Definition at line 70 of file XmStamper.cpp.
References m_outPts.
GetSegments()
virtual const VecInt2d& xms::XmStamperImpl::GetSegments () inline override virtual
returns breaklines created by the stamp operation.
Returns
segments.
Definition at line 75 of file XmStamper.cpp.
References m_breaklines.
InputErrorsFound()
bool xms::XmStamperImpl::InputErrorsFound ()
Checks for input errors.
Returns
true or false.
Definition at line 281 of file XmStamper.cpp.
References xms::XmStamperIo::m_centerLine, xms::XmStamperIo::m_cs, m_interp, m_io, xmlog::warning, XM_ENSURE_TRUE, and XM_LOG.
Referenced by DoStamp().
SetObserver()
virtual void xms::XmStamperImpl::SetObserver (BSHP< Observer > a_) inline override virtual
sets the observer class to get feedback on the meshing process
Parameters
[in] a_ Observer class to provide feedback.
Definition at line 86 of file XmStamper.cpp.
References m_observer.
Member Data Documentation
m_interp
BSHP<XmStampInterpCrossSection> xms::XmStamperImpl::m_interp
cross section interpolator. Interpolates cross sections to points along the polyline in the XmStamperIo class.
Definition at line 94 of file XmStamper.cpp.
Referenced by FillStamperIoFromCenterlineProfile(), InputErrorsFound(), and InterpolateMissingCrossSections().
m_io
XmStamperIo xms::XmStamperImpl::m_io
inputs to the stamp operation
Definition at line 89 of file XmStamper.cpp.
Referenced by AppendTinAndBreakLines(), Convert3dPtsToVec(), ConvertCrossSectionsTo3d(), ConvertEndCapsTo3d(), CreateBathymetryIntersector(), CreateBreakLines(), CreateOutputs(), DecomposeCenterLine(), DoStamp(), InputErrorsFound(), InterpolateMissingCrossSections(), IntersectCenterLineWithBathemetry(), IntersectWithTin(), and WriteInputsForDebug().
The documentation for this class was generated from the following file:
/home/conan/xmsstamper/stamper/XmStamper.cpp