xmsstamper: xms::XmStampRaster Class Reference
xms::XmStampRaster Class Reference
Raster defined using a non-rotated cartesian axis for use in XmStamper.
#include <XmStamperIo.h>
Public Types
enum XmRasterFormatEnum { RS_ARCINFO_ASCII }
/breif enum the identify the format of the raster
Public Member Functions
XmStampRaster (const int a_numPixelsX, const int a_numPixelsY, const double a_pixelSizeX, const double a_pixelSizeY, const Pt2d &a_min, const std::vector< double > &a_vals, const int a_noData)
Constructor that sets all the raster values.
XmStampRaster ()
Default Constructor.
int GetCellIndexFromColRow (const int a_col, const int a_row) const
Gets the zero-based cell index from the given column and row.
void GetColRowFromCellIndex (const int a_index, int &a_col, int &a_row) const
Gets the zero-based column and row from the cell index.
Pt2d GetLocationFromCellIndex (const int a_index) const
Gets the location of the cell center from the zero-based cell index.
void WriteGridFile (const std::string &a_fileName, const XmRasterFormatEnum a_format)
Writes the raster in the given format to the given filename.
void WriteToFile (std::ofstream &a_file, const std::string &a_cardName) const
Writes the XmStampRaster class information to a file.
bool ReadFromFile (std::ifstream &a_file)
Reads the XmStampRaster class information to a file.
Public Attributes
int m_numPixelsX
Number of pixels in the X-direction (Required)
int m_numPixelsY
Number of pixels in the Y-direction (Required)
double m_pixelSizeX
Pixel size in the X-direction (Required)
double m_pixelSizeY
Pixel size in the Y-direction (Required)
Pt2d m_min
Minimum (lower left) X, Y coordinate of the raster at the center of the raster cell (Required)
std::vector< double > m_vals
int m_noData
NO DATA value for the raster (typically XM_NODATA)
Detailed Description
Raster defined using a non-rotated cartesian axis for use in XmStamper.
Definition at line 34 of file XmStamperIo.h.
Constructor & Destructor Documentation
XmStampRaster()
xms::XmStampRaster::XmStampRaster (const int a_numPixelsX, const int a_numPixelsY, const double a_pixelSizeX, const double a_pixelSizeY, const Pt2d & a_min, const std::vector< double > & a_vals, const int a_noData)
Constructor that sets all the raster values.
Parameters
[in] a_numPixelsX number of pixels in x direction
[in] a_numPixelsY number of pixels in y direction
[in] a_pixelSizeX size of the pixels in the x direction
[in] a_pixelSizeY size of the pixels in the y direction
[in] a_min The bottom left corner (x,y) of the raster
[in] a_vals The raster values
[in] a_noData The "no data" (or inactive) value to identify raster pixels where no value exists.
Definition at line 290 of file XmStamperIo.cpp.
Member Function Documentation
GetCellIndexFromColRow()
int xms::XmStampRaster::GetCellIndexFromColRow (const int a_col, const int a_row) const
Gets the zero-based cell index from the given column and row.
Parameters
[in] a_col The zero-based column index for the raster.
[in] a_row The zero-based row index for the raster.
Returns
The zero-based cell index from the given a_col, a_row.
Definition at line 320 of file XmStamperIo.cpp.
References m_numPixelsX, and m_numPixelsY.
Referenced by XmStampIntermediateTests::test_BuildRasterAndGetCellValue().
GetColRowFromCellIndex()
void xms::XmStampRaster::GetColRowFromCellIndex (const int a_index, int & a_col, int & a_row) const
Gets the zero-based column and row from the cell index.
Parameters
[in] a_index The zero-based raster cell index.
[out] a_col The zero-based column index for the raster.
[out] a_row The zero-based row index for the raster.
Definition at line 334 of file XmStamperIo.cpp.
References m_numPixelsX, and m_numPixelsY.
Referenced by GetLocationFromCellIndex().
GetLocationFromCellIndex()
Pt2d xms::XmStampRaster::GetLocationFromCellIndex (const int a_index) const
Gets the location of the cell center from the zero-based cell index.
Parameters
[in] a_index The zero-based raster cell index.
Returns
The location of the cell with the given index.
Definition at line 348 of file XmStamperIo.cpp.
References GetColRowFromCellIndex(), m_min, m_numPixelsY, m_pixelSizeX, and m_pixelSizeY.
ReadFromFile()
bool xms::XmStampRaster::ReadFromFile (std::ifstream & a_file)
Reads the XmStampRaster class information to a file.
Parameters
[in] a_file The input file.
Returns
true if file read is successful. false if errors encountered.
Definition at line 415 of file XmStamperIo.cpp.
References m_min, m_noData, m_numPixelsX, m_numPixelsY, m_pixelSizeX, m_pixelSizeY, m_vals, stEqualNoCase(), and XM_ENSURE_TRUE.
WriteGridFile()
void xms::XmStampRaster::WriteGridFile (const std::string & a_fileName, const XmRasterFormatEnum a_format)
Writes the raster in the given format to the given filename.
Parameters
[in] a_fileName The output raster filename.
[in] a_format The output raster format.
Definition at line 366 of file XmStamperIo.cpp.
References m_min, m_noData, m_numPixelsX, m_numPixelsY, m_pixelSizeX, m_pixelSizeY, m_vals, and XM_ENSURE_TRUE.
Referenced by TutStampingUnitTests::test_StampCutEmbankment(), TutStampingUnitTests::test_StampFillEmbankment(), TutStampingUnitTests::test_StampGuidebank(), TutStampingUnitTests::test_StampIntersectBathymetry(), TutStampingUnitTests::test_StampSlopedAbutment(), and TutStampingUnitTests::test_StampWingWall().
WriteToFile()
void xms::XmStampRaster::WriteToFile (std::ofstream & a_file, const std::string & a_cardName) const
Writes the XmStampRaster class information to a file.
Parameters
[in] a_file The output file.
[in] a_cardName The card name to be written to the output file.
Definition at line 397 of file XmStamperIo.cpp.
References m_min, m_noData, m_numPixelsX, m_numPixelsY, m_pixelSizeX, m_pixelSizeY, m_vals, and XM_ENSURE_TRUE.
Member Data Documentation
m_vals
std::vector<double> xms::XmStampRaster::m_vals
Raster values defined from the top left corner to the bottom right corner (Required) Use the m_noData value to specify a cell value with no data.
Definition at line 47 of file XmStamperIo.h.
Referenced by xms::XmStamperImpl::DoStamp(), ReadFromFile(), XmStampIntermediateTests::test_BuildRasterAndGetCellValue(), WriteGridFile(), and WriteToFile().
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/XmStamperIo.h
/home/conan/xmsstamper/stamper/XmStamperIo.cpp