xmsstamper: xms::XmSlopedAbutment Class Reference
xms::XmSlopedAbutment Class Reference
Abutment definition for feature stamp end cap.
#include <XmStamperIo.h>
Public Member Functions
void WriteToFile (std::ofstream &a_file, const std::string &a_cardName) const
Writes the XmSlopedAbutment class information to a file.
bool ReadFromFile (std::ifstream &a_file)
Reads the XmSlopedAbutment class information to a file.
Public Attributes
double m_maxX
max distance from center line
VecPt3d m_slope
x,y pairs defining slope from center line
Detailed Description
Abutment definition for feature stamp end cap.
Definition at line 77 of file XmStamperIo.h.
Member Function Documentation
ReadFromFile()
bool xms::XmSlopedAbutment::ReadFromFile (std::ifstream & a_file)
Reads the XmSlopedAbutment class information to a file.
Parameters
[in] a_file The input file.
Returns
true if file read is successful. false if errors encountered.
Definition at line 465 of file XmStamperIo.cpp.
References m_maxX, m_slope, stEqualNoCase(), and XM_ENSURE_TRUE.
Referenced by xms::XmStamperEndCap::ReadFromFile().
WriteToFile()
void xms::XmSlopedAbutment::WriteToFile (std::ofstream & a_file, const std::string & a_cardName) const
Writes the XmSlopedAbutment class information to a file.
Parameters
[in] a_file The output file.
[in] a_cardName The card name to be written to the output file.
Definition at line 453 of file XmStamperIo.cpp.
References m_maxX, m_slope, and XM_ENSURE_TRUE.
Referenced by xms::XmStamperEndCap::WriteToFile().
The documentation for this class was generated from the following files:
/home/conan/xmsstamper/stamper/XmStamperIo.h
/home/conan/xmsstamper/stamper/XmStamperIo.cpp