move /Y rasterTestFiles\xmsng_out.txt rasterTestFiles\xmsng_base.txt
move /Y test_GuideBank01\xmsng_out.txt test_GuideBank01\xmsng_base.txt
move /Y test_GuideBank02\xmsng_out.txt test_GuideBank02\xmsng_base.txt
move /Y test_GuideBank03\xmsng_out.txt test_GuideBank03\xmsng_base.txt
move /Y test_GuideBank04\xmsng_out.txt test_GuideBank04\xmsng_base.txt
move /Y test_GuideBank05\xmsng_out.txt test_GuideBank05\xmsng_base.txt
move /Y test_GuideBank06\xmsng_out.txt test_GuideBank06\xmsng_base.txt
move /Y test_GuideBank07\xmsng_out.txt test_GuideBank07\xmsng_base.txt
move /Y test_GuideBank08_cut\xmsng_out.txt test_GuideBank08_cut\xmsng_base.txt
move /Y test_intersectBathymetry01\xmsng_out.txt test_intersectBathymetry01\xmsng_base.txt
move /Y test_intersectBathymetry02\xmsng_out.txt test_intersectBathymetry02\xmsng_base.txt
move /Y test_intersectBathymetry03\xmsng_out.txt test_intersectBathymetry03\xmsng_base.txt
move /Y test_intersectBathymetry04\xmsng_out.txt test_intersectBathymetry04\xmsng_base.txt
move /Y test_intersectBathymetry05\xmsng_out.txt test_intersectBathymetry05\xmsng_base.txt
move /Y test_intersectBathymetry06\xmsng_out.txt test_intersectBathymetry06\xmsng_base.txt
move /Y test_intersectBathymetry07\xmsng_out.txt test_intersectBathymetry07\xmsng_base.txt
move /Y test_intersectBathymetry08\xmsng_out.txt test_intersectBathymetry08\xmsng_base.txt
move /Y test_intersectBathymetry09\xmsng_out.txt test_intersectBathymetry09\xmsng_base.txt
move /Y test_intersectBathymetry10\xmsng_out.txt test_intersectBathymetry10\xmsng_base.txt
move /Y test_intersections\xmsng_out.txt test_intersections\xmsng_base.txt
move /Y test_SlopedAbutment01\xmsng_out.txt test_SlopedAbutment01\xmsng_base.txt
move /Y test_SlopedAbutment02\xmsng_out.txt test_SlopedAbutment02\xmsng_base.txt
move /Y test_SlopedAbutment03\xmsng_out.txt test_SlopedAbutment03\xmsng_base.txt
move /Y test_slopedAbutment04_cut\xmsng_out.txt test_slopedAbutment04_cut\xmsng_base.txt
move /Y test_StampIntersectBathymetry\xmsng_out.txt test_StampIntersectBathymetry\xmsng_base.txt
move /Y test_WingWall01\xmsng_out.txt test_WingWall01\xmsng_base.txt
move /Y test_WingWall02\xmsng_out.txt test_WingWall02\xmsng_base.txt
move /Y test_WingWall03\xmsng_out.txt test_WingWall03\xmsng_base.txt
move /Y test_wingWall04_cut\xmsng_out.txt test_wingWall04_cut\xmsng_base.txt
